"use client"

import { useState, useEffect, useRef } from "react"
import { Button } from "@/components/ui/button"
import { ActionButton } from "@/components/ui/action-button"
import { Alert } from "@/components/ui/alert"
import { Layout } from "@/components/layout"
import { Header } from "@/components/header"
import { clearAuth, createPost, createNote, updatePost, updateNote, deletePost, deleteNote, getPostContent, getNoteContent } from "@/app/actions/posts"
import { toast } from "sonner"
import { cn } from "@/lib/utils"
import { Loader2, Github } from "lucide-react"
import { PageLoader } from "@/components/ui/loading-spinner"
import { Card } from "@/components/ui/card"
import { SubmitButton } from "@/components/ui/submit-button"
import {
  AdminHeader,
  StatsSection,
  PostForm,
  NoteForm,
  ContentEditor,
} from "@/components/pages/admin"
import { ContentList } from "@/components/pages/admin/content-list"

type ContentType = "post" | "note"
type ViewMode = "edit" | "preview" | "split"

export default function AdminPage() {
  const [isAuthenticated, setIsAuthenticated] = useState<boolean | null>(null)
  const [username, setUsername] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState("")
  const [success, setSuccess] = useState("")
  const [contentType, setContentType] = useState<ContentType>("note")
  const [viewMode, setViewMode] = useState<ViewMode>("split")
  const [showList, setShowList] = useState(false)
  const [editingId, setEditingId] = useState<string | null>(null)
  
  // 创作统计数据
  const [stats, setStats] = useState<{
    posts: { date: string }[]
    notes: { date: string }[]
    tags: { tag: string; count: number }[]
    stats: {
      totalPosts: number
      totalNotes: number
      thisMonthPosts: number
      thisMonthNotes: number
      thisWeekPosts: number
      thisWeekNotes: number
    }
  } | null>(null)

  // 列表数据
  const [postsList, setPostsList] = useState<Array<{ id: string; title: string; date: string; tags: string[] }>>([])
  const [notesList, setNotesList] = useState<Array<{ id: string; date: string; content: string }>>([])
  const [listLoading, setListLoading] = useState(false)

  // 用于同步滚动的 ref
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const previewRef = useRef<HTMLDivElement>(null)
  const isScrollingRef = useRef(false)

  // 获取当天日期（本地时间）
  const getTodayDate = (): string => {
    const today = new Date()
    const year = today.getFullYear()
    const month = String(today.getMonth() + 1).padStart(2, '0')
    const day = String(today.getDate()).padStart(2, '0')
    return `${year}-${month}-${day}`
  }

  // 表单状态
  const [formData, setFormData] = useState({
    title: "",
    content: "",
    date: getTodayDate(),
    tags: [] as string[],
    id: "",
  })

  // 计算自动生成的 ID（用于显示）
  const getAutoGeneratedId = (): string => {
    if (formData.id && formData.id.trim()) {
      return formData.id.trim().toLowerCase()
    }
    
    if (contentType === "post" && formData.title && formData.title.trim()) {
      const generated = formData.title
        .toLowerCase()
        .replace(/[^\w\s-]/g, "")
        .replace(/\s+/g, "-")
        .replace(/-+/g, "-")
        .replace(/^-|-$/g, "")
        .trim()
        .substring(0, 50)
      
      if (generated && generated.length > 0) {
        return generated
      }
    }
    
    // 备用方案：日期 + 时间戳 + 随机后缀
    const dateStr = formData.date.replace(/-/g, "")
    const timestamp = Date.now().toString().slice(-8)
    const randomSuffix = Math.random().toString(36).substring(2, 6)
    const prefix = contentType === "post" ? "post" : "note"
    return `${prefix}-${dateStr}-${timestamp}-${randomSuffix}`
  }

  const autoGeneratedId = getAutoGeneratedId()

  // 检查认证状态和 URL 参数
  useEffect(() => {
    async function checkAuthStatus() {
      try {
        const response = await fetch("/api/admin/check")
        const data = await response.json()
        setIsAuthenticated(data.authenticated)
        setUsername(data.username || null)
        
        // 认证成功后，确保日期是当天
        if (data.authenticated) {
          const today = getTodayDate()
          setFormData(prev => ({
            ...prev,
            date: today
          }))
        }
      } catch (error) {
        setIsAuthenticated(false)
      }
    }

    // 检查 URL 参数中的错误或成功消息
    const params = new URLSearchParams(window.location.search)
    const errorParam = params.get("error")
    const successParam = params.get("success")

    if (errorParam) {
      const errorMessage = decodeURIComponent(errorParam)
      setError(errorMessage)
      toast.error(errorMessage)
      window.history.replaceState({}, "", "/admin")
    }

    if (successParam) {
      const successMessage = decodeURIComponent(successParam)
      toast.success(successMessage, {
        duration: 3000,
      })
      window.history.replaceState({}, "", "/admin")
    }

    checkAuthStatus()
  }, [])
  
  // 获取创作统计数据
  const fetchStats = async () => {
    try {
      const response = await fetch("/api/admin/stats")
      if (response.ok) {
        const data = await response.json()
        setStats(data)
      }
    } catch (error) {
      console.error("Failed to fetch stats:", error)
    }
  }

  // 获取内容列表
  const fetchContentList = async () => {
    setListLoading(true)
    try {
      if (contentType === "post") {
        const response = await fetch("/api/admin/posts")
        if (response.ok) {
          const data = await response.json()
          setPostsList(data)
        }
      } else {
        const response = await fetch("/api/admin/notes")
        if (response.ok) {
          const data = await response.json()
          setNotesList(data)
        }
      }
    } catch (error) {
      console.error("Failed to fetch content list:", error)
      toast.error("获取列表失败")
    } finally {
      setListLoading(false)
    }
  }
  
  useEffect(() => {
    if (isAuthenticated) {
      fetchStats()
    }
  }, [isAuthenticated])

  // 当切换内容类型或显示列表时，刷新列表
  useEffect(() => {
    if (isAuthenticated && showList) {
      fetchContentList()
    }
  }, [isAuthenticated, contentType, showList])

  // 处理 GitHub OAuth 登录
  function handleGitHubLogin() {
    window.location.href = "/api/auth/github"
  }

  // 处理登出
  async function handleLogout() {
    await clearAuth()
    setIsAuthenticated(false)
    setUsername(null)
    setSuccess("已登出")
  }

  // 切换内容类型时重置表单
  useEffect(() => {
    if (contentType === "note") {
      const today = getTodayDate()
      setFormData({
        title: "",
        content: formData.content,
        date: today,
        tags: [],
        id: "",
      })
      // 随笔模式下自动聚焦到输入框
      setTimeout(() => {
        textareaRef.current?.focus()
      }, 100)
    }
  }, [contentType])
  
  // 随笔模式下，页面加载时自动聚焦
  useEffect(() => {
    if (contentType === "note" && isAuthenticated) {
      setTimeout(() => {
        textareaRef.current?.focus()
      }, 300)
    }
  }, [isAuthenticated, contentType])

  // 处理编辑
  const handleEdit = async (id: string) => {
    setLoading(true)
    setError("")
    try {
      if (contentType === "post") {
        const result = await getPostContent(id)
        if (result.success && result.post) {
          setFormData({
            title: result.post.title,
            content: result.post.content,
            date: result.post.date.split("T")[0], // 从 ISO 格式提取日期部分
            tags: result.post.tags || [],
            id: result.post.id,
          })
          setEditingId(id)
          setShowList(false)
          toast.success("已加载文章内容")
        } else {
          setError(result.message || "加载文章失败")
          toast.error(result.message || "加载文章失败")
        }
      } else {
        const result = await getNoteContent(id)
        if (result.success && result.note) {
          setFormData({
            title: "",
            content: result.note.content,
            date: result.note.date.split("T")[0], // 从 ISO 格式提取日期部分
            tags: [],
            id: result.note.id,
          })
          setEditingId(id)
          setShowList(false)
          toast.success("已加载随笔内容")
        } else {
          setError(result.message || "加载随笔失败")
          toast.error(result.message || "加载随笔失败")
        }
      }
    } catch (err) {
      const errorMessage = "加载内容失败，请重试"
      setError(errorMessage)
      toast.error(errorMessage)
    } finally {
      setLoading(false)
    }
  }

  // 处理删除
  const handleDelete = async (id: string) => {
    try {
      let result
      if (contentType === "post") {
        result = await deletePost(id)
      } else {
        result = await deleteNote(id)
      }

      if (result.success) {
        // 刷新列表和统计数据
        fetchContentList()
        fetchStats()
        // 如果删除的是正在编辑的内容，清空表单
        if (editingId === id) {
          setFormData({
            title: "",
            content: "",
            date: getTodayDate(),
            tags: [],
            id: "",
          })
          setEditingId(null)
        }
      } else {
        throw new Error(result.message)
      }
    } catch (err) {
      throw err
    }
  }

  // 处理提交
  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()

    // 基本验证
    if (contentType === "post" && !formData.title.trim()) {
      setError("请输入文章标题")
      toast.error("请输入文章标题")
      return
    }

    if (!formData.content.trim()) {
      setError("请输入内容")
      toast.error("请输入内容")
      return
    }

    if (!formData.date) {
      setError("请选择日期")
      toast.error("请选择日期")
      return
    }

    setLoading(true)
    setError("")
    setSuccess("")

    try {
      let result
      if (editingId) {
        // 更新模式
        if (contentType === "post") {
          result = await updatePost(editingId, {
            title: formData.title,
            content: formData.content,
            date: formData.date,
            tags: formData.tags,
          })
        } else {
          result = await updateNote(editingId, {
            content: formData.content,
            date: formData.date,
          })
        }
      } else {
        // 创建模式
        if (contentType === "post") {
          result = await createPost({
            title: formData.title,
            content: formData.content,
            date: formData.date,
            tags: formData.tags,
            id: formData.id || undefined,
          })
        } else {
          result = await createNote({
            content: formData.content,
            date: formData.date,
            id: formData.id || undefined,
          })
        }
      }

      if (result.success) {
        // 更新模式下使用 editingId，创建模式下使用 result.id（如果存在）
        const actualId = editingId || ("id" in result ? result.id : formData.id || autoGeneratedId)
        const successMessage = `${result.message}。${contentType === "post" ? "文章" : "随笔"}已提交到 GitHub，Vercel 将自动重新部署（通常需要 1-2 分钟）`
        const detailMessage = `文件 ID: ${actualId}`
        setSuccess(successMessage)
        toast.success(`${successMessage}\n${detailMessage}`, {
          duration: 6000,
        })
        // 清空表单
        setFormData({
          title: "",
          content: "",
          date: getTodayDate(),
          tags: [],
          id: "",
        })
        setEditingId(null)
        // 刷新统计数据和列表
        fetchStats()
        if (showList) {
          fetchContentList()
        }
      } else {
        setError(result.message)
        toast.error(result.message)
      }
    } catch (err) {
      const errorMessage = "提交失败，请重试"
      setError(errorMessage)
      toast.error(errorMessage)
    } finally {
      setLoading(false)
    }
  }

  // 切换到新建模式
  const handleNew = () => {
    setFormData({
      title: "",
      content: "",
      date: getTodayDate(),
      tags: [],
      id: "",
    })
    setEditingId(null)
    setShowList(false)
  }

  // 如果还在检查认证状态，显示加载中
  if (isAuthenticated === null) {
    return (
      <Layout>
        <div className="max-w-2xl mx-auto px-4 py-6">
          <Header showBackButton={true} />
          <PageLoader
            message="正在验证身份..."
            subMessage="稍等片刻"
            size="lg"
          />
        </div>
      </Layout>
    )
  }

  // 如果未认证，显示登录页面
  if (!isAuthenticated) {
    return (
      <Layout>
        <div className="max-w-2xl mx-auto px-4 py-6">
          <Header showBackButton={true} />
          <div className="max-w-md mx-auto mt-12">
            <h1 className="text-2xl font-bold mb-4">你居然发现这里了！🎉</h1>
            <p className="text-sm text-zinc-600 dark:text-zinc-400 mb-2">
              这里是我的秘密基地，只有我知道怎么进来 😎
            </p>
            <p className="text-xs text-zinc-500 dark:text-zinc-500 mb-6 italic">
              不过既然你找到了，那就用 GitHub 登录试试看吧～
            </p>
            {error && (
              <Alert variant="destructive" className="mb-4">
                {error}
              </Alert>
            )}
            {success && (
              <Alert variant="success" className="mb-4">
                {success}
              </Alert>
            )}
            <ActionButton
              icon={loading ? Loader2 : Github}
              iconClassName={loading ? "animate-spin" : undefined}
              onClick={handleGitHubLogin}
              disabled={loading}
              className="w-full justify-center"
            >
              {loading ? "登录中..." : "用 GitHub 登录试试"}
            </ActionButton>
            <p className="mt-4 text-xs text-zinc-500 dark:text-zinc-400 text-center italic">
              提示：只有仓库所有者或协作者才能进来哦
            </p>
            
            {/* 有趣的内容 */}
            <div className="mt-12 pt-8 border-t border-zinc-200 dark:border-zinc-800">
              <div className="text-center space-y-4">
                <div className="text-4xl mb-4">🔐</div>
                <p className="text-sm text-zinc-500 dark:text-zinc-500 italic">
                  "好奇心是发现秘密的第一步"
                </p>
                <div className="flex justify-center gap-2 text-2xl mt-6">
                  <span>🎨</span>
                  <span>💻</span>
                  <span>📝</span>
                  <span>✨</span>
                </div>
                <p className="text-xs text-zinc-400 dark:text-zinc-600 mt-4">
                  如果你真的进来了，记得帮我写点好东西 😊
                </p>
                <Card variant="muted" size="md">
                  <p className="text-xs text-zinc-600 dark:text-zinc-400 leading-relaxed">
                    <span className="font-semibold">小贴士：</span>
                    <br />
                    这个页面是我用来管理博客内容的，如果你也想搭建类似的博客，可以看看我的 GitHub 仓库源码哦～
                  </p>
                </Card>
              </div>
            </div>
          </div>
        </div>
      </Layout>
    )
  }

  // 已认证，显示管理界面
  return (
    <Layout>
      <div className="max-w-7xl mx-auto px-4 py-6">
        <Header showBackButton={true} />
        
        <AdminHeader
          username={username}
          contentType={contentType}
          viewMode={viewMode}
          showList={showList}
          onContentTypeChange={(type) => {
            setContentType(type)
            setShowList(false)
            handleNew()
          }}
          onViewModeChange={setViewMode}
          onLogout={handleLogout}
          onToggleList={() => {
            setShowList(!showList)
            if (!showList) {
              fetchContentList()
            }
          }}
        />

        {/* 内容列表视图 */}
        {showList ? (
          <div className="bg-transparent">
            <h2 className="text-lg font-semibold mb-4 text-zinc-900 dark:text-zinc-100">
              {contentType === "post" ? "文章列表" : "随笔列表"}
            </h2>
            <ContentList
              contentType={contentType}
              posts={postsList}
              notes={notesList}
              onEdit={handleEdit}
              onDelete={handleDelete}
              loading={listLoading}
            />
          </div>
        ) : (
          <>
            {/* 创作统计区域 - 仅在文章模式下显示 */}
            {stats && contentType === "post" && (
              <StatsSection
                stats={stats}
                selectedTags={formData.tags}
                onTagToggle={(tag: string) => {
                  setFormData(prev => ({
                    ...prev,
                    tags: prev.tags.includes(tag)
                      ? prev.tags.filter(t => t !== tag)
                      : [...prev.tags, tag]
                  }))
                }}
                title={formData.title}
                date={formData.date}
                onTitleChange={(title: string) => setFormData(prev => ({ ...prev, title }))}
                onDateChange={(date: string) => setFormData(prev => ({ ...prev, date }))}
                onTagsChange={(tags: string[]) => setFormData(prev => ({ ...prev, tags }))}
              />
            )}

            <form onSubmit={handleSubmit} className={cn("space-y-0", contentType === "note" && "space-y-0")}>
          {/* 文章模式 - 整合设计 */}
          {contentType === "post" && (
            <div className="bg-transparent dark:bg-transparent rounded-xl overflow-hidden">
              
              {/* 内容编辑和预览 - 无缝连接 */}
              <ContentEditor
                content={formData.content}
                viewMode={viewMode}
                onContentChange={(content: string) => setFormData(prev => ({ ...prev, content }))}
              />
              
              {/* 提交按钮 - 整合在底部 */}
              <div className="flex justify-end items-center gap-3 py-4">
                {editingId && (
                  <Button
                    type="button"
                    variant="outline"
                    onClick={handleNew}
                    className={cn(
                      "h-9 px-6 rounded-xl text-sm font-medium",
                      "bg-white dark:bg-zinc-800 border border-zinc-300 dark:border-zinc-700",
                      "text-zinc-700 dark:text-zinc-300",
                      "hover:bg-zinc-50 dark:hover:bg-zinc-700"
                    )}
                  >
                    取消编辑
                  </Button>
                )}
                <SubmitButton
                  loading={loading}
                  editing={!!editingId}
                  editText="更新文章"
                  createText="发布文章"
                  editingLoadingText="更新中..."
                  creatingLoadingText="提交中..."
                />
              </div>
            </div>
          )}
          
          {/* 随笔模式 */}
          {contentType === "note" && (
            <NoteForm
              content={formData.content}
              date={formData.date}
              autoGeneratedId={autoGeneratedId}
              viewMode={viewMode}
              loading={loading}
              editing={!!editingId}
              onContentChange={(content: string) => setFormData(prev => ({ ...prev, content }))}
              onDateChange={(date: string) => setFormData(prev => ({ ...prev, date }))}
              onViewModeChange={setViewMode}
              onCancelEdit={handleNew}
            />
          )}
        </form>
          </>
        )}
      </div>
    </Layout>
  )
}
