"use client"

import { useState, useEffect, useRef } from "react"
import { Button } from "@/components/ui/button"
import { Layout } from "@/components/layout"
import { Header } from "@/components/header"
import { clearAuth, createPost, createNote } from "@/app/actions/posts"
import { Alert } from "@/components/ui/alert"
import { toast } from "sonner"
import { cn } from "@/lib/utils"
import { Loader2 } from "lucide-react"
import {
  AdminHeader,
  StatsSection,
  PostForm,
  NoteForm,
  ContentEditor,
} from "@/components/pages/admin"

type ContentType = "post" | "note"
type ViewMode = "edit" | "preview" | "split"

export default function AdminPage() {
  const [isAuthenticated, setIsAuthenticated] = useState<boolean | null>(null)
  const [username, setUsername] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState("")
  const [success, setSuccess] = useState("")
  const [contentType, setContentType] = useState<ContentType>("note")
  const [viewMode, setViewMode] = useState<ViewMode>("split")
  
  // 创作统计数据
  const [stats, setStats] = useState<{
    posts: { date: string }[]
    notes: { date: string }[]
    tags: { tag: string; count: number }[]
    stats: {
      totalPosts: number
      totalNotes: number
      thisMonthPosts: number
      thisMonthNotes: number
      thisWeekPosts: number
      thisWeekNotes: number
    }
  } | null>(null)

  // 用于同步滚动的 ref
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const previewRef = useRef<HTMLDivElement>(null)
  const isScrollingRef = useRef(false)

  // 获取当天日期（本地时间）
  const getTodayDate = (): string => {
    const today = new Date()
    const year = today.getFullYear()
    const month = String(today.getMonth() + 1).padStart(2, '0')
    const day = String(today.getDate()).padStart(2, '0')
    return `${year}-${month}-${day}`
  }

  // 表单状态
  const [formData, setFormData] = useState({
    title: "",
    content: "",
    date: getTodayDate(),
    tags: [] as string[],
    id: "",
  })

  // 计算自动生成的 ID（用于显示）
  const getAutoGeneratedId = (): string => {
    if (formData.id && formData.id.trim()) {
      return formData.id.trim().toLowerCase()
    }
    
    if (contentType === "post" && formData.title && formData.title.trim()) {
      const generated = formData.title
        .toLowerCase()
        .replace(/[^\w\s-]/g, "")
        .replace(/\s+/g, "-")
        .replace(/-+/g, "-")
        .replace(/^-|-$/g, "")
        .trim()
        .substring(0, 50)
      
      if (generated && generated.length > 0) {
        return generated
      }
    }
    
    // 备用方案：日期 + 时间戳 + 随机后缀
    const dateStr = formData.date.replace(/-/g, "")
    const timestamp = Date.now().toString().slice(-8)
    const randomSuffix = Math.random().toString(36).substring(2, 6)
    const prefix = contentType === "post" ? "post" : "note"
    return `${prefix}-${dateStr}-${timestamp}-${randomSuffix}`
  }

  const autoGeneratedId = getAutoGeneratedId()

  // 检查认证状态和 URL 参数
  useEffect(() => {
    async function checkAuthStatus() {
      try {
        const response = await fetch("/api/admin/check")
        const data = await response.json()
        setIsAuthenticated(data.authenticated)
        setUsername(data.username || null)
        
        // 认证成功后，确保日期是当天
        if (data.authenticated) {
          const today = getTodayDate()
          setFormData(prev => ({
            ...prev,
            date: today
          }))
        }
      } catch (error) {
        setIsAuthenticated(false)
      }
    }

    // 检查 URL 参数中的错误或成功消息
    const params = new URLSearchParams(window.location.search)
    const errorParam = params.get("error")
    const successParam = params.get("success")

    if (errorParam) {
      const errorMessage = decodeURIComponent(errorParam)
      setError(errorMessage)
      toast.error(errorMessage)
      window.history.replaceState({}, "", "/admin")
    }

    if (successParam) {
      const successMessage = decodeURIComponent(successParam)
      toast.success(successMessage, {
        duration: 3000,
      })
      window.history.replaceState({}, "", "/admin")
    }

    checkAuthStatus()
  }, [])
  
  // 获取创作统计数据
  const fetchStats = async () => {
    try {
      const response = await fetch("/api/admin/stats")
      if (response.ok) {
        const data = await response.json()
        setStats(data)
      }
    } catch (error) {
      console.error("Failed to fetch stats:", error)
    }
  }
  
  useEffect(() => {
    if (isAuthenticated) {
      fetchStats()
    }
  }, [isAuthenticated])

  // 处理 GitHub OAuth 登录
  function handleGitHubLogin() {
    window.location.href = "/api/auth/github"
  }

  // 处理登出
  async function handleLogout() {
    await clearAuth()
    setIsAuthenticated(false)
    setUsername(null)
    setSuccess("已登出")
  }

  // 切换内容类型时重置表单
  useEffect(() => {
    if (contentType === "note") {
      const today = getTodayDate()
      setFormData({
        title: "",
        content: formData.content,
        date: today,
        tags: [],
        id: "",
      })
      // 随笔模式下自动聚焦到输入框
      setTimeout(() => {
        textareaRef.current?.focus()
      }, 100)
    }
  }, [contentType])
  
  // 随笔模式下，页面加载时自动聚焦
  useEffect(() => {
    if (contentType === "note" && isAuthenticated) {
      setTimeout(() => {
        textareaRef.current?.focus()
      }, 300)
    }
  }, [isAuthenticated, contentType])

  // 处理提交
  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()

    // 基本验证
    if (contentType === "post" && !formData.title.trim()) {
      setError("请输入文章标题")
      toast.error("请输入文章标题")
      return
    }

    if (!formData.content.trim()) {
      setError("请输入内容")
      toast.error("请输入内容")
      return
    }

    if (!formData.date) {
      setError("请选择日期")
      toast.error("请选择日期")
      return
    }

    setLoading(true)
    setError("")
    setSuccess("")

    try {
      let result
      if (contentType === "post") {
        result = await createPost({
          title: formData.title,
          content: formData.content,
          date: formData.date,
          tags: formData.tags,
          id: undefined,
        })
      } else {
        result = await createNote({
          content: formData.content,
          date: formData.date,
          id: undefined,
        })
      }

      if (result.success) {
        const actualId = result.id || autoGeneratedId
        const successMessage = `${result.message}。${contentType === "post" ? "文章" : "随笔"}已提交到 GitHub，Vercel 将自动重新部署（通常需要 1-2 分钟）`
        const detailMessage = `文件 ID: ${actualId}`
        setSuccess(successMessage)
        toast.success(`${successMessage}\n${detailMessage}`, {
          duration: 6000,
        })
        // 清空表单
        setFormData({
          title: "",
          content: "",
          date: getTodayDate(),
          tags: [],
          id: "",
        })
        // 刷新统计数据
        fetchStats()
      } else {
        setError(result.message)
        toast.error(result.message)
      }
    } catch (err) {
      const errorMessage = "提交失败，请重试"
      setError(errorMessage)
      toast.error(errorMessage)
    } finally {
      setLoading(false)
    }
  }

  // 如果还在检查认证状态，显示加载中
  if (isAuthenticated === null) {
    return (
      <Layout>
        <div className="max-w-2xl mx-auto px-4 py-6">
          <Header showBackButton={true} />
          <div className="flex flex-col items-center justify-center min-h-[60vh]">
            <div className="relative">
              <div className="absolute inset-0 bg-gradient-to-r from-zinc-200 to-zinc-300 dark:from-zinc-700 dark:to-zinc-800 rounded-full blur-xl opacity-50 animate-pulse"></div>
              <div className="relative bg-white dark:bg-zinc-900 rounded-full p-6 shadow-lg border border-zinc-200 dark:border-zinc-800">
                <Loader2 className="w-8 h-8 text-zinc-600 dark:text-zinc-400 animate-spin" />
              </div>
            </div>
            <p className="mt-6 text-sm font-medium text-zinc-600 dark:text-zinc-400">
              正在验证身份...
            </p>
            <p className="mt-2 text-xs text-zinc-500 dark:text-zinc-500 italic">
              稍等片刻
            </p>
          </div>
        </div>
      </Layout>
    )
  }

  // 如果未认证，显示登录页面
  if (!isAuthenticated) {
    return (
      <Layout>
        <div className="max-w-2xl mx-auto px-4 py-6">
          <Header showBackButton={true} />
          <div className="max-w-md mx-auto mt-12">
            <h1 className="text-2xl font-bold mb-4">你居然发现这里了！🎉</h1>
            <p className="text-sm text-zinc-600 dark:text-zinc-400 mb-2">
              这里是我的秘密基地，只有我知道怎么进来 😎
            </p>
            <p className="text-xs text-zinc-500 dark:text-zinc-500 mb-6 italic">
              不过既然你找到了，那就用 GitHub 登录试试看吧～
            </p>
            {error && (
              <div className="mb-4 p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-md text-red-700 dark:text-red-400 text-sm">
                {error}
              </div>
            )}
            {success && (
              <div className="mb-4 p-4 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-md text-green-700 dark:text-green-400 text-sm">
                {success}
              </div>
            )}
            <Button
              onClick={handleGitHubLogin}
              disabled={loading}
              className="w-full"
            >
              {loading ? "登录中..." : "用 GitHub 登录试试"}
            </Button>
            <p className="mt-4 text-xs text-zinc-500 dark:text-zinc-400 text-center italic">
              提示：只有仓库所有者或协作者才能进来哦
            </p>
            
            {/* 有趣的内容 */}
            <div className="mt-12 pt-8 border-t border-zinc-200 dark:border-zinc-800">
              <div className="text-center space-y-4">
                <div className="text-4xl mb-4">🔐</div>
                <p className="text-sm text-zinc-500 dark:text-zinc-500 italic">
                  "好奇心是发现秘密的第一步"
                </p>
                <div className="flex justify-center gap-2 text-2xl mt-6">
                  <span>🎨</span>
                  <span>💻</span>
                  <span>📝</span>
                  <span>✨</span>
                </div>
                <p className="text-xs text-zinc-400 dark:text-zinc-600 mt-4">
                  如果你真的进来了，记得帮我写点好东西 😊
                </p>
                <div className="mt-6 p-4 bg-zinc-50 dark:bg-zinc-900/30 rounded-lg border border-zinc-200 dark:border-zinc-800">
                  <p className="text-xs text-zinc-600 dark:text-zinc-400 leading-relaxed">
                    <span className="font-semibold">小贴士：</span>
                    <br />
                    这个页面是我用来管理博客内容的，如果你也想搭建类似的博客，可以看看我的 GitHub 仓库源码哦～
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Layout>
    )
  }

  // 已认证，显示管理界面
  return (
    <Layout>
      <div className="max-w-7xl mx-auto px-4 py-6">
        <Header showBackButton={true} />
        
        <AdminHeader
          username={username}
          contentType={contentType}
          viewMode={viewMode}
          onContentTypeChange={setContentType}
          onViewModeChange={setViewMode}
          onLogout={handleLogout}
        />

        {/* 消息提示 */}
        {error && (
          <Alert
            variant="destructive"
            onClose={() => setError("")}
            autoClose={true}
            autoCloseDelay={8000}
            className="mb-4"
          >
            {error}
          </Alert>
        )}

        {success && (
          <Alert
            variant="success"
            onClose={() => setSuccess("")}
            autoClose={true}
            autoCloseDelay={10000}
            className="mb-4"
          >
            {success}
          </Alert>
        )}

        {/* 创作统计区域 - 仅在文章模式下显示 */}
        {stats && contentType === "post" && (
          <StatsSection
            stats={stats}
            selectedTags={formData.tags}
            onTagToggle={(tag: string) => {
              setFormData(prev => ({
                ...prev,
                tags: prev.tags.includes(tag)
                  ? prev.tags.filter(t => t !== tag)
                  : [...prev.tags, tag]
              }))
            }}
            title={formData.title}
            date={formData.date}
            onTitleChange={(title: string) => setFormData(prev => ({ ...prev, title }))}
            onDateChange={(date: string) => setFormData(prev => ({ ...prev, date }))}
            onTagsChange={(tags: string[]) => setFormData(prev => ({ ...prev, tags }))}
          />
        )}

        <form onSubmit={handleSubmit} className={cn("space-y-0", contentType === "note" && "space-y-0")}>
          {/* 文章模式 - 整合设计 */}
          {contentType === "post" && (
            <div className="bg-transparent dark:bg-transparent rounded-xl overflow-hidden">
              
              {/* 内容编辑和预览 - 无缝连接 */}
              <ContentEditor
                content={formData.content}
                viewMode={viewMode}
                onContentChange={(content: string) => setFormData(prev => ({ ...prev, content }))}
              />
              
              {/* 提交按钮 - 整合在底部 */}
              <div className="flex justify-end py-4">
                <Button 
                  type="submit" 
                  disabled={loading} 
                  className={cn(
                    "h-9 px-6 rounded-xl text-sm font-medium",
                    "bg-zinc-900 text-white dark:bg-zinc-50 dark:text-zinc-900",
                    "border border-zinc-900 dark:border-zinc-50",
                    "shadow-sm hover:shadow-md transition-all",
                    "disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:shadow-sm"
                  )}
                >
                  {loading ? (
                    <span className="flex items-center gap-2">
                      <Loader2 className="w-4 h-4 animate-spin" />
                      提交中...
                    </span>
                ) : (
                  "发布文章"
                )}
                </Button>
              </div>
            </div>
          )}
          
          {/* 随笔模式 */}
          {contentType === "note" && (
            <NoteForm
              content={formData.content}
              date={formData.date}
              autoGeneratedId={autoGeneratedId}
              viewMode={viewMode}
              loading={loading}
              onContentChange={(content: string) => setFormData(prev => ({ ...prev, content }))}
              onDateChange={(date: string) => setFormData(prev => ({ ...prev, date }))}
              onViewModeChange={setViewMode}
            />
          )}
        </form>
      </div>
    </Layout>
  )
}
