"use client"

import { useState, useEffect, useRef } from "react"
import { Button } from "@/components/ui/button"
import { Layout } from "@/components/layout"
import { Header } from "@/components/header"
import { clearAuth, createPost, createNote } from "@/app/actions/posts"
import { PostPreview } from "@/components/post-preview"
import { NotePreview } from "@/components/note-preview"
import { DatePicker } from "@/components/ui/date-picker"
import { TagInput } from "@/components/ui/tag-input"
import { FileIdInput } from "@/components/ui/file-id-input"
import { Alert } from "@/components/ui/alert"
import { toast } from "sonner"

type ContentType = "post" | "note"

export default function AdminPage() {
  const [isAuthenticated, setIsAuthenticated] = useState<boolean | null>(null)
  const [username, setUsername] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState("")
  const [success, setSuccess] = useState("")
  const [contentType, setContentType] = useState<ContentType>("post")
  const [viewMode, setViewMode] = useState<"edit" | "preview" | "split">("split")
  
  // 用于同步滚动的 ref
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const previewRef = useRef<HTMLDivElement>(null)
  const isScrollingRef = useRef(false)

  // 表单状态
  const [formData, setFormData] = useState({
    title: "",
    content: "",
    date: new Date().toISOString().split("T")[0],
    tags: [] as string[],
    id: "",
  })

  // 计算自动生成的 ID（用于显示）
  const getAutoGeneratedId = (): string => {
    if (formData.id && formData.id.trim()) {
      return formData.id.trim().toLowerCase()
    }
    
    if (contentType === "post" && formData.title && formData.title.trim()) {
      const generated = formData.title
        .toLowerCase()
        .replace(/[^\w\s-]/g, "")
        .replace(/\s+/g, "-")
        .replace(/-+/g, "-")
        .replace(/^-|-$/g, "")
        .trim()
        .substring(0, 50)
      
      if (generated && generated.length > 0) {
        return generated
      }
    }
    
    // 备用方案：日期 + 时间戳 + 随机后缀
    const dateStr = formData.date.replace(/-/g, "")
    const timestamp = Date.now().toString().slice(-8)
    const randomSuffix = Math.random().toString(36).substring(2, 6)
    const prefix = contentType === "post" ? "post" : "note"
    return `${prefix}-${dateStr}-${timestamp}-${randomSuffix}`
  }

  const autoGeneratedId = getAutoGeneratedId()

  // 检查认证状态和 URL 参数
  useEffect(() => {
    async function checkAuthStatus() {
      try {
        const response = await fetch("/api/admin/check")
        const data = await response.json()
        setIsAuthenticated(data.authenticated)
        setUsername(data.username || null)
      } catch (error) {
        setIsAuthenticated(false)
      }
    }

    // 检查 URL 参数中的错误或成功消息
    const params = new URLSearchParams(window.location.search)
    const errorParam = params.get("error")
    const successParam = params.get("success")

    if (errorParam) {
      const errorMessage = decodeURIComponent(errorParam)
      setError(errorMessage)
      toast.error(errorMessage)
      window.history.replaceState({}, "", "/admin")
    }

    if (successParam) {
      const successMessage = decodeURIComponent(successParam)
      toast.success(successMessage, {
        duration: 3000,
      })
      window.history.replaceState({}, "", "/admin")
    }

    checkAuthStatus()
  }, [])

  // 处理 GitHub OAuth 登录
  function handleGitHubLogin() {
    window.location.href = "/api/auth/github"
  }

  // 处理登出
  async function handleLogout() {
    await clearAuth()
    setIsAuthenticated(false)
    setUsername(null)
    setSuccess("已登出")
  }

  // 切换内容类型时重置表单
  useEffect(() => {
    if (contentType === "note") {
      setFormData({
        title: "",
        content: formData.content,
        date: formData.date,
        tags: [],
        id: "",
      })
    }
  }, [contentType])

  // 同步滚动功能
  useEffect(() => {
    if (viewMode !== "split" || !textareaRef.current || !previewRef.current) {
      return
    }

    const textarea = textareaRef.current
    const preview = previewRef.current

    const handleTextareaScroll = () => {
      if (isScrollingRef.current) return
      isScrollingRef.current = true

      const textareaScrollTop = textarea.scrollTop
      const textareaScrollHeight = textarea.scrollHeight - textarea.clientHeight
      const textareaScrollRatio = textareaScrollHeight > 0 ? textareaScrollTop / textareaScrollHeight : 0

      const previewScrollHeight = preview.scrollHeight - preview.clientHeight
      const previewScrollTop = previewScrollHeight * textareaScrollRatio

      preview.scrollTop = previewScrollTop

      requestAnimationFrame(() => {
        isScrollingRef.current = false
      })
    }

    const handlePreviewScroll = () => {
      if (isScrollingRef.current) return
      isScrollingRef.current = true

      const previewScrollTop = preview.scrollTop
      const previewScrollHeight = preview.scrollHeight - preview.clientHeight
      const previewScrollRatio = previewScrollHeight > 0 ? previewScrollTop / previewScrollHeight : 0

      const textareaScrollHeight = textarea.scrollHeight - textarea.clientHeight
      const textareaScrollTop = textareaScrollHeight * previewScrollRatio

      textarea.scrollTop = textareaScrollTop

      requestAnimationFrame(() => {
        isScrollingRef.current = false
      })
    }

    textarea.addEventListener("scroll", handleTextareaScroll)
    preview.addEventListener("scroll", handlePreviewScroll)

    return () => {
      textarea.removeEventListener("scroll", handleTextareaScroll)
      preview.removeEventListener("scroll", handlePreviewScroll)
    }
  }, [viewMode, formData.content])

  // 处理提交
  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()

    // 基本验证
    if (contentType === "post" && !formData.title.trim()) {
      setError("请输入文章标题")
      toast.error("请输入文章标题")
      return
    }

    if (!formData.content.trim()) {
      setError("请输入内容")
      toast.error("请输入内容")
      return
    }

    if (!formData.date) {
      setError("请选择日期")
      toast.error("请选择日期")
      return
    }

    // 验证文件 ID（如果提供了）
    if (formData.id && formData.id.trim()) {
      const idPattern = /^[a-z0-9_-]+$/
      if (!idPattern.test(formData.id.trim().toLowerCase())) {
        setError("文件 ID 格式无效，只能包含小写字母、数字、连字符和下划线")
        toast.error("文件 ID 格式无效")
        return
      }
    }

    setLoading(true)
    setError("")
    setSuccess("")

    try {
      let result
      if (contentType === "post") {
        result = await createPost({
          title: formData.title,
          content: formData.content,
          date: formData.date,
          tags: formData.tags,
          id: formData.id || undefined,
        })
      } else {
        result = await createNote({
          content: formData.content,
          date: formData.date,
          id: formData.id || undefined,
        })
      }

      if (result.success) {
        const actualId = result.id || autoGeneratedId
        const successMessage = `${result.message}。${contentType === "post" ? "文章" : "随笔"}已提交到 GitHub，Vercel 将自动重新部署（通常需要 1-2 分钟）`
        const detailMessage = `文件 ID: ${actualId}`
        setSuccess(successMessage)
        toast.success(`${successMessage}\n${detailMessage}`, {
          duration: 6000,
        })
        // 清空表单
        setFormData({
          title: "",
          content: "",
          date: new Date().toISOString().split("T")[0],
          tags: [],
          id: "",
        })
      } else {
        setError(result.message)
        toast.error(result.message)
      }
    } catch (err) {
      const errorMessage = "提交失败，请重试"
      setError(errorMessage)
      toast.error(errorMessage)
    } finally {
      setLoading(false)
    }
  }

  // 如果还在检查认证状态，显示加载中
  if (isAuthenticated === null) {
    return (
      <Layout>
        <div className="max-w-2xl mx-auto px-4 py-6">
          <Header showBackButton={true} />
          <div className="text-center py-12">检查认证状态...</div>
        </div>
      </Layout>
    )
  }

  // 如果未认证，显示登录页面
  if (!isAuthenticated) {
    return (
      <Layout>
        <div className="max-w-2xl mx-auto px-4 py-6">
          <Header showBackButton={true} />
          <div className="max-w-md mx-auto mt-12">
            <h1 className="text-2xl font-bold mb-6">管理员登录</h1>
            <p className="text-sm text-zinc-600 dark:text-zinc-400 mb-6">
              使用 GitHub 账号登录以验证您的身份
            </p>
            {error && (
              <div className="mb-4 p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-md text-red-700 dark:text-red-400 text-sm">
                {error}
              </div>
            )}
            {success && (
              <div className="mb-4 p-4 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-md text-green-700 dark:text-green-400 text-sm">
                {success}
              </div>
            )}
            <Button
              onClick={handleGitHubLogin}
              disabled={loading}
              className="w-full"
            >
              {loading ? "登录中..." : "使用 GitHub 登录"}
            </Button>
            <p className="mt-4 text-xs text-zinc-500 dark:text-zinc-400 text-center">
              只有仓库所有者或协作者才能访问
            </p>
          </div>
        </div>
      </Layout>
    )
  }

  // 已认证，显示管理界面
  return (
    <Layout>
      <div className="max-w-7xl mx-auto px-4 py-6">
        <Header showBackButton={true} />
        
        {/* 头部 */}
        <div className="flex justify-between items-center mb-8">
          <div>
            {username && (() => {
              const hour = new Date().getHours()
              let greeting = "你好"
              if (hour >= 5 && hour < 12) {
                greeting = "早上好"
              } else if (hour >= 12 && hour < 18) {
                greeting = "下午好"
              } else if (hour >= 18 && hour < 22) {
                greeting = "晚上好"
              } else {
                greeting = "夜深了"
              }
              return (
                <>
                  <h1 className="text-3xl font-bold text-zinc-900 dark:text-zinc-100">
                    {greeting}，{username}！
                  </h1>
                  <p className="text-base text-zinc-600 dark:text-zinc-400 mt-2">
                    今天想写点什么？✨
                  </p>
                </>
              )
            })()}
            {!username && (
              <h1 className="text-3xl font-bold text-zinc-900 dark:text-zinc-100">内容管理</h1>
            )}
          </div>
          <Button onClick={handleLogout} variant="outline" className="shadow-sm">
            登出
          </Button>
        </div>

        {/* 类型选择 */}
        <div className="mb-6 flex flex-wrap gap-4 items-center bg-white dark:bg-zinc-900/50 rounded-lg border border-zinc-200 dark:border-zinc-800 p-4 shadow-sm">
          <div className="flex gap-2">
            <Button
              type="button"
              variant={contentType === "post" ? "default" : "outline"}
              onClick={() => setContentType("post")}
              className="shadow-sm"
            >
              博客文章
            </Button>
            <Button
              type="button"
              variant={contentType === "note" ? "default" : "outline"}
              onClick={() => setContentType("note")}
              className="shadow-sm"
            >
              随笔
            </Button>
          </div>
          <div className="flex gap-2 ml-auto">
            <Button
              type="button"
              variant={viewMode === "edit" ? "default" : "outline"}
              size="sm"
              onClick={() => setViewMode("edit")}
              className="shadow-sm"
            >
              编辑
            </Button>
            <Button
              type="button"
              variant={viewMode === "split" ? "default" : "outline"}
              size="sm"
              onClick={() => setViewMode("split")}
              className="shadow-sm"
            >
              分栏
            </Button>
            <Button
              type="button"
              variant={viewMode === "preview" ? "default" : "outline"}
              size="sm"
              onClick={() => setViewMode("preview")}
              className="shadow-sm"
            >
              预览
            </Button>
          </div>
        </div>

        {/* 消息提示 */}
        {error && (
          <Alert
            variant="destructive"
            onClose={() => setError("")}
            autoClose={true}
            autoCloseDelay={8000}
            className="mb-4"
          >
            {error}
          </Alert>
        )}

        {success && (
          <Alert
            variant="success"
            onClose={() => setSuccess("")}
            autoClose={true}
            autoCloseDelay={10000}
            className="mb-4"
          >
            {success}
          </Alert>
        )}

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* 基础信息 */}
          <div className="bg-white dark:bg-zinc-900/50 rounded-lg border border-zinc-200 dark:border-zinc-800 p-6 shadow-sm">
            {contentType === "post" ? (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <label htmlFor="title" className="block text-sm font-medium text-zinc-700 dark:text-zinc-300">
                    标题 <span className="text-red-500">*</span>
                  </label>
                  <input
                    id="title"
                    type="text"
                    value={formData.title}
                    onChange={(e) =>
                      setFormData({ ...formData, title: e.target.value })
                    }
                    className="w-full h-10 px-4 border border-zinc-300 dark:border-zinc-700 rounded-md dark:bg-zinc-950 dark:text-zinc-100 bg-white text-zinc-900 focus:outline-none focus:ring-2 focus:ring-zinc-500 dark:focus:ring-zinc-400 focus:border-transparent transition-all"
                    required
                  />
                </div>

                <div className="space-y-2">
                  <label htmlFor="date" className="block text-sm font-medium text-zinc-700 dark:text-zinc-300">
                    日期 <span className="text-red-500">*</span>
                  </label>
                  <DatePicker
                    value={formData.date}
                    onChange={(date) =>
                      setFormData({ ...formData, date })
                    }
                    placeholder="选择日期"
                    className="h-10"
                  />
                </div>

                <div className="space-y-2">
                  <label htmlFor="tags" className="block text-sm font-medium text-zinc-700 dark:text-zinc-300">
                    标签
                  </label>
                  <TagInput
                    value={formData.tags}
                    onChange={(tags) => setFormData({ ...formData, tags })}
                    placeholder="输入标签后按回车或逗号"
                  />
                </div>

                <div className="space-y-2">
                  <label htmlFor="id" className="block text-sm font-medium text-zinc-700 dark:text-zinc-300">
                    文件 ID（可选，留空将自动生成）
                  </label>
                  <FileIdInput
                    value={formData.id}
                    onChange={(id) => setFormData({ ...formData, id })}
                    contentType="post"
                    placeholder="例如: my-new-post"
                  />
                  {!formData.id && (
                    <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-2">
                      将自动生成 ID: <span className="font-mono text-zinc-700 dark:text-zinc-300">{autoGeneratedId}</span>
                    </p>
                  )}
                </div>
              </div>
            ) : (
              <div className="space-y-6">
                <div className="space-y-2">
                  <label htmlFor="date" className="block text-sm font-medium text-zinc-700 dark:text-zinc-300">
                    日期 <span className="text-red-500">*</span>
                  </label>
                  <DatePicker
                    value={formData.date}
                    onChange={(date) =>
                      setFormData({ ...formData, date })
                    }
                    placeholder="选择日期"
                    className="h-10"
                  />
                </div>
                <div className="space-y-2">
                  <label className="block text-sm font-medium text-zinc-700 dark:text-zinc-300">
                    文件 ID（自动生成）
                  </label>
                  <div className="h-10 px-4 border border-zinc-300 dark:border-zinc-700 rounded-md dark:bg-zinc-950 dark:text-zinc-100 bg-zinc-50 flex items-center">
                    <span className="font-mono text-sm text-zinc-700 dark:text-zinc-300">{autoGeneratedId}</span>
                  </div>
                  <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-2">
                    随笔将使用此 ID 创建文件
                  </p>
                </div>
              </div>
            )}
          </div>

          {/* 内容编辑和预览 */}
          <div
            className={`grid gap-6 ${
              viewMode === "split"
                ? "grid-cols-1 lg:grid-cols-2"
                : "grid-cols-1"
            }`}
          >
            {/* 编辑区域 */}
            {(viewMode === "edit" || viewMode === "split") && (
              <div className="flex flex-col bg-white dark:bg-zinc-900/50 rounded-lg border border-zinc-200 dark:border-zinc-800 p-6 shadow-sm">
                <label
                  htmlFor="content"
                  className="block text-sm font-medium mb-3 text-zinc-700 dark:text-zinc-300"
                >
                  {contentType === "post" ? (
                    <>内容（Markdown） <span className="text-red-500">*</span></>
                  ) : (
                    <>内容 <span className="text-red-500">*</span> <span className="text-xs font-normal text-zinc-500 dark:text-zinc-400 ml-2">（支持简单文本，Markdown 可选）</span></>
                  )}
                </label>
                <textarea
                  ref={textareaRef}
                  id="content"
                  value={formData.content}
                  onChange={(e) =>
                    setFormData({ ...formData, content: e.target.value })
                  }
                  className={`w-full px-4 py-3 border border-zinc-300 dark:border-zinc-700 rounded-md text-sm dark:bg-zinc-950 dark:text-zinc-100 bg-white text-zinc-900 resize-none flex-1 overflow-y-auto focus:outline-none focus:ring-2 focus:ring-zinc-500 dark:focus:ring-zinc-400 focus:border-transparent transition-all ${
                    contentType === "post" ? "font-mono" : ""
                  }`}
                  style={{ 
                    height: viewMode === "split" 
                      ? (contentType === "post" ? "600px" : "300px")
                      : "auto",
                    minHeight: viewMode === "split"
                      ? (contentType === "post" ? "600px" : "300px")
                      : (contentType === "post" ? "600px" : "200px"),
                    maxHeight: viewMode === "split"
                      ? (contentType === "post" ? "600px" : "300px")
                      : "none"
                  }}
                  required
                  placeholder={
                    contentType === "post"
                      ? "在这里输入 Markdown 内容..."
                      : "写下你的想法、感受或日常..."
                  }
                />
              </div>
            )}

            {/* 预览区域 */}
            {(viewMode === "preview" || viewMode === "split") && (
              <div className="flex flex-col bg-white dark:bg-zinc-900/50 rounded-lg border border-zinc-200 dark:border-zinc-800 p-6 shadow-sm">
                <label className="block text-sm font-medium mb-3 text-zinc-700 dark:text-zinc-300">
                  预览
                </label>
                <div 
                  ref={previewRef}
                  className="border border-zinc-300 dark:border-zinc-700 rounded-md p-4 bg-white dark:bg-zinc-950 overflow-y-auto flex-1"
                  style={{ 
                    height: viewMode === "split"
                      ? (contentType === "post" ? "600px" : "300px")
                      : "auto",
                    minHeight: viewMode === "split"
                      ? (contentType === "post" ? "600px" : "300px")
                      : (contentType === "post" ? "600px" : "200px"),
                    maxHeight: viewMode === "split"
                      ? (contentType === "post" ? "600px" : "300px")
                      : "none"
                  }}
                >
                  {contentType === "note" ? (
                    <NotePreview content={formData.content} date={formData.date} />
                  ) : (
                    <PostPreview content={formData.content} />
                  )}
                </div>
              </div>
            )}
          </div>

          {/* 提交按钮 */}
          <div className="flex justify-end">
            <Button 
              type="submit" 
              disabled={loading} 
              className="min-w-[200px] h-11 text-base font-medium shadow-sm hover:shadow-md transition-shadow"
            >
              {loading
                ? "提交中..."
                : `创建${contentType === "post" ? "文章" : "随笔"}`}
            </Button>
          </div>
        </form>

        {/* 使用说明 */}
        <div className="mt-8 p-6 bg-gradient-to-br from-zinc-50 to-zinc-100 dark:from-zinc-900 dark:to-zinc-950 rounded-lg border border-zinc-200 dark:border-zinc-800 shadow-sm">
          <h3 className="font-semibold mb-3 text-zinc-800 dark:text-zinc-200">使用说明</h3>
          <ul className="list-disc list-inside space-y-2 text-sm text-zinc-700 dark:text-zinc-300">
            {contentType === "post" ? (
              <>
                <li>博客文章需要标题、日期和内容，可选标签</li>
                <li>支持完整的 Markdown 语法，包括代码块、数学公式、表格等</li>
                <li>内容提交后会通过 GitHub API 创建文件</li>
                <li>Vercel 会自动检测 GitHub 变更并重新部署</li>
                <li>通常需要 1-2 分钟才能在网站上看到新文章</li>
                <li>如果文件 ID 已存在，会自动生成新的 ID</li>
              </>
            ) : (
              <>
                <li>随笔只需要日期和内容，更简洁随意</li>
                <li>建议使用简单文本，Markdown 语法可选但不推荐复杂结构</li>
                <li>内容提交后会通过 GitHub API 创建文件</li>
                <li>Vercel 会自动检测 GitHub 变更并重新部署</li>
                <li>通常需要 1-2 分钟才能在网站上看到新随笔</li>
              </>
            )}
          </ul>
        </div>
      </div>
    </Layout>
  )
}
