"use client"

import { useState, useEffect, useRef } from "react"
import { Button } from "@/components/ui/button"
import { Layout } from "@/components/layout"
import { Header } from "@/components/header"
import { clearAuth, createPost, createNote, updatePost, updateNote, deletePost, deleteNote, getPostContent, getNoteContent } from "@/app/actions/posts"
import { toast } from "sonner"
import { cn } from "@/lib/utils"
import { SubmitButton } from "@/components/ui/submit-button"
import {
  AdminHeader,
  StatsSection,
  PostForm,
  NoteForm,
  ContentEditor,
} from "@/components/pages/admin"
import { ContentList } from "@/components/pages/admin/content-list"
import { formatFileIdInput, generateFileId, generateFallbackId } from "@/lib/file-id"
import { AdminUnauthenticatedView } from "@/components/pages/admin/admin-unauthenticated-view"
import { AdminLoadingView } from "@/components/pages/admin/admin-loading-view"

type ContentType = "post" | "note"
type ViewMode = "edit" | "preview" | "split"

export function AdminApp() {
  const [isAuthenticated, setIsAuthenticated] = useState<boolean | null>(null)
  const [username, setUsername] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState("")
  const [success, setSuccess] = useState("")
  const [contentType, setContentType] = useState<ContentType>("note")
  const [viewMode, setViewMode] = useState<ViewMode>("split")
  const [showList, setShowList] = useState(false)
  const [editingId, setEditingId] = useState<string | null>(null)
  
  const [stats, setStats] = useState<{
    posts: { date: string }[]
    notes: { date: string }[]
    tags: { tag: string; count: number }[]
    stats: {
      totalPosts: number
      totalNotes: number
      thisMonthPosts: number
      thisMonthNotes: number
      thisWeekPosts: number
      thisWeekNotes: number
    }
  } | null>(null)

  const [postsList, setPostsList] = useState<Array<{ id: string; title: string; date: string; tags: string[] }>>([])
  const [notesList, setNotesList] = useState<Array<{ id: string; date: string; content: string }>>([])
  const [listLoading, setListLoading] = useState(false)

  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const previewRef = useRef<HTMLDivElement>(null)
  const isScrollingRef = useRef(false)

  const getTodayDate = (): string => {
    const today = new Date()
    const year = today.getFullYear()
    const month = String(today.getMonth() + 1).padStart(2, '0')
    const day = String(today.getDate()).padStart(2, '0')
    return `${year}-${month}-${day}`
  }

  const [formData, setFormData] = useState({
    title: "",
    content: "",
    date: getTodayDate(),
    tags: [] as string[],
    id: "",
  })

  const getAutoGeneratedId = (): string => {
    if (formData.id && formData.id.trim()) {
      return formatFileIdInput(formData.id)
    }
    
    if (contentType === "post" && formData.title && formData.title.trim()) {
      const generated = generateFileId(formData.title)
      if (generated && generated.length > 0) {
        return generated
      }
    }
    
    return generateFallbackId(contentType, formData.date)
  }

  const autoGeneratedId = getAutoGeneratedId()

  useEffect(() => {
    async function checkAuthStatus() {
      try {
        const response = await fetch("/api/admin/check")
        const data = await response.json()
        setIsAuthenticated(data.authenticated)
        setUsername(data.username || null)
        
        if (data.authenticated) {
          const today = getTodayDate()
          setFormData(prev => ({
            ...prev,
            date: today
          }))
        }
      } catch (error) {
        setIsAuthenticated(false)
      }
    }

    const params = new URLSearchParams(window.location.search)
    const errorParam = params.get("error")
    const successParam = params.get("success")

    if (errorParam) {
      const errorMessage = decodeURIComponent(errorParam)
      setError(errorMessage)
      toast.error(errorMessage)
      window.history.replaceState({}, "", "/admin")
    }

    if (successParam) {
      const successMessage = decodeURIComponent(successParam)
      toast.success(successMessage, {
        duration: 3000,
      })
      window.history.replaceState({}, "", "/admin")
    }

    checkAuthStatus()
  }, [])
  
  const fetchStats = async () => {
    try {
      const response = await fetch("/api/admin/stats")
      if (response.ok) {
        const data = await response.json()
        setStats(data)
      }
    } catch (error) {
      console.error("Failed to fetch stats:", error)
    }
  }

  const fetchContentList = async () => {
    setListLoading(true)
    try {
      if (contentType === "post") {
        const response = await fetch("/api/admin/posts")
        if (response.ok) {
          const data = await response.json()
          setPostsList(data)
        }
      } else {
        const response = await fetch("/api/admin/notes")
        if (response.ok) {
          const data = await response.json()
          setNotesList(data)
        }
      }
    } catch (error) {
      console.error("Failed to fetch content list:", error)
      toast.error("获取列表失败")
    } finally {
      setListLoading(false)
    }
  }
  
  useEffect(() => {
    if (isAuthenticated) {
      fetchStats()
    }
  }, [isAuthenticated])

  useEffect(() => {
    if (isAuthenticated && showList) {
      fetchContentList()
    }
  }, [isAuthenticated, contentType, showList])

  function handleGitHubLogin() {
    window.location.href = "/api/auth/github"
  }

  async function handleLogout() {
    await clearAuth()
    setIsAuthenticated(false)
    setUsername(null)
    setSuccess("已登出")
  }

  useEffect(() => {
    if (contentType === "note") {
      const today = getTodayDate()
      setFormData({
        title: "",
        content: formData.content,
        date: today,
        tags: [],
        id: "",
      })
      setTimeout(() => {
        textareaRef.current?.focus()
      }, 100)
    }
  }, [contentType])
  
  useEffect(() => {
    if (contentType === "note" && isAuthenticated) {
      setTimeout(() => {
        textareaRef.current?.focus()
      }, 300)
    }
  }, [isAuthenticated, contentType])

  const handleEdit = async (id: string) => {
    setLoading(true)
    setError("")
    try {
      if (contentType === "post") {
        const result = await getPostContent(id)
        if (result.success && result.post) {
          setFormData({
            title: result.post.title,
            content: result.post.content,
            date: result.post.date.split("T")[0],
            tags: result.post.tags || [],
            id: result.post.id,
          })
          setEditingId(id)
          setShowList(false)
          toast.success("已加载文章内容")
        } else {
          setError(result.message || "加载文章失败")
          toast.error(result.message || "加载文章失败")
        }
      } else {
        const result = await getNoteContent(id)
        if (result.success && result.note) {
          setFormData({
            title: "",
            content: result.note.content,
            date: result.note.date.split("T")[0],
            tags: [],
            id: result.note.id,
          })
          setEditingId(id)
          setShowList(false)
          toast.success("已加载随笔内容")
        } else {
          setError(result.message || "加载随笔失败")
          toast.error(result.message || "加载随笔失败")
        }
      }
    } catch (err) {
      const errorMessage = "加载内容失败，请重试"
      setError(errorMessage)
      toast.error(errorMessage)
    } finally {
      setLoading(false)
    }
  }

  const handleDelete = async (id: string) => {
    try {
      let result
      if (contentType === "post") {
        result = await deletePost(id)
      } else {
        result = await deleteNote(id)
      }

      if (result.success) {
        fetchContentList()
        fetchStats()
        if (editingId === id) {
          setFormData({
            title: "",
            content: "",
            date: getTodayDate(),
            tags: [],
            id: "",
          })
          setEditingId(null)
        }
      } else {
        throw new Error(result.message)
      }
    } catch (err) {
      throw err
    }
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()

    if (contentType === "post" && !formData.title.trim()) {
      setError("请输入文章标题")
      toast.error("请输入文章标题")
      return
    }

    if (!formData.content.trim()) {
      setError("请输入内容")
      toast.error("请输入内容")
      return
    }

    if (!formData.date) {
      setError("请选择日期")
      toast.error("请选择日期")
      return
    }

    setLoading(true)
    setError("")
    setSuccess("")

    try {
      let result
      if (editingId) {
        if (contentType === "post") {
          result = await updatePost(editingId, {
            title: formData.title,
            content: formData.content,
            date: formData.date,
            tags: formData.tags,
          })
        } else {
          result = await updateNote(editingId, {
            content: formData.content,
            date: formData.date,
          })
        }
      } else {
        if (contentType === "post") {
          result = await createPost({
            title: formData.title,
            content: formData.content,
            date: formData.date,
            tags: formData.tags,
            id: formData.id || undefined,
          })
        } else {
          result = await createNote({
            content: formData.content,
            date: formData.date,
            id: formData.id || undefined,
          })
        }
      }

      if (result.success) {
        const actualId = editingId || ("id" in result ? result.id : formData.id || autoGeneratedId)
        const successMessage = `${result.message}。${contentType === "post" ? "文章" : "随笔"}已提交到 GitHub，Vercel 将自动重新部署（通常需要 1-2 分钟）`
        const detailMessage = `文件 ID: ${actualId}`
        setSuccess(successMessage)
        toast.success(`${successMessage}\n${detailMessage}`, {
          duration: 6000,
        })
        setFormData({
          title: "",
          content: "",
          date: getTodayDate(),
          tags: [],
          id: "",
        })
        setEditingId(null)
        fetchStats()
        if (showList) {
          fetchContentList()
        }
      } else {
        setError(result.message)
        toast.error(result.message)
      }
    } catch (err) {
      const errorMessage = "提交失败，请重试"
      setError(errorMessage)
      toast.error(errorMessage)
    } finally {
      setLoading(false)
    }
  }

  const handleNew = () => {
    setFormData({
      title: "",
      content: "",
      date: getTodayDate(),
      tags: [],
      id: "",
    })
    setEditingId(null)
    setShowList(false)
  }

  if (isAuthenticated === null) {
    return <AdminLoadingView />
  }

  if (!isAuthenticated) {
    return (
      <Layout>
        <div className="max-w-2xl mx-auto px-4 py-6">
          <Header showBackButton={true} />
          <AdminUnauthenticatedView
            error={error}
            success={success}
            loading={loading}
            onGitHubLogin={handleGitHubLogin}
          />
        </div>
      </Layout>
    )
  }

  return (
    <Layout>
      <div className="max-w-7xl mx-auto px-4 py-6 overflow-x-hidden">
        <Header showBackButton={true} />
        
        <AdminHeader
          username={username}
          contentType={contentType}
          viewMode={viewMode}
          showList={showList}
          onContentTypeChange={(type) => {
            setContentType(type)
            setShowList(false)
            handleNew()
          }}
          onViewModeChange={setViewMode}
          onLogout={handleLogout}
          onToggleList={() => {
            setShowList(!showList)
            if (!showList) {
              fetchContentList()
            }
          }}
        />

        {showList ? (
          <div className="bg-transparent">
            <h2 className="text-lg font-semibold mb-4 text-zinc-900 dark:text-zinc-100">
              {contentType === "post" ? "文章列表" : "随笔列表"}
            </h2>
            <ContentList
              contentType={contentType}
              posts={postsList}
              notes={notesList}
              onEdit={handleEdit}
              onDelete={handleDelete}
              loading={listLoading}
            />
          </div>
        ) : (
          <>
            {stats && contentType === "post" && (
              <StatsSection
                stats={stats}
                selectedTags={formData.tags}
                onTagToggle={(tag: string) => {
                  setFormData(prev => ({
                    ...prev,
                    tags: prev.tags.includes(tag)
                      ? prev.tags.filter(t => t !== tag)
                      : [...prev.tags, tag]
                  }))
                }}
                title={formData.title}
                date={formData.date}
                onTitleChange={(title: string) => setFormData(prev => ({ ...prev, title }))}
                onDateChange={(date: string) => setFormData(prev => ({ ...prev, date }))}
                onTagsChange={(tags: string[]) => setFormData(prev => ({ ...prev, tags }))}
              />
            )}

            <form onSubmit={handleSubmit} className={cn("space-y-0", contentType === "note" && "space-y-0")}>
              {contentType === "post" && (
                <div className="bg-transparent dark:bg-transparent rounded-xl overflow-hidden">
                  <ContentEditor
                    content={formData.content}
                    viewMode={viewMode}
                    onContentChange={(content: string) => setFormData(prev => ({ ...prev, content }))}
                  />
                  <div className="flex justify-end items-center gap-3 py-4">
                    {editingId && (
                      <Button
                        type="button"
                        variant="outline"
                        onClick={handleNew}
                        className={cn(
                          "h-9 px-6 rounded-xl text-sm font-medium",
                          "bg-white dark:bg-zinc-800 border border-zinc-300 dark:border-zinc-700",
                          "text-zinc-700 dark:text-zinc-300",
                          "hover:bg-zinc-50 dark:hover:bg-zinc-700"
                        )}
                      >
                        取消编辑
                      </Button>
                    )}
                    <SubmitButton
                      loading={loading}
                      editing={!!editingId}
                      editText="更新文章"
                      createText="发布文章"
                      editingLoadingText="更新中..."
                      creatingLoadingText="提交中..."
                    />
                  </div>
                </div>
              )}
              
              {contentType === "note" && (
                <NoteForm
                  content={formData.content}
                  date={formData.date}
                  autoGeneratedId={autoGeneratedId}
                  viewMode={viewMode}
                  loading={loading}
                  editing={!!editingId}
                  onContentChange={(content: string) => setFormData(prev => ({ ...prev, content }))}
                  onDateChange={(date: string) => setFormData(prev => ({ ...prev, date }))}
                  onViewModeChange={setViewMode}
                  onCancelEdit={handleNew}
                />
              )}
            </form>
          </>
        )}
      </div>
    </Layout>
  )
}

