"use client"

import { useRef, useEffect, useState } from "react"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { DecorativeLine } from "@/components/ui/decorative-line"
import { SubmitButton } from "@/components/ui/submit-button"
import { DatePicker } from "@/components/ui/date-picker"
import { NotePreview } from "@/components/ui/note-preview"
import { cn } from "@/lib/utils"

type ViewMode = "edit" | "preview" | "split"

interface NoteFormProps {
  content: string
  date: string
  autoGeneratedId: string
  viewMode: ViewMode
  loading: boolean
  editing?: boolean
  onContentChange: (content: string) => void
  onDateChange: (date: string) => void
  onViewModeChange: (mode: ViewMode) => void
  onCancelEdit?: () => void
}

export function NoteForm({
  content,
  date,
  autoGeneratedId,
  viewMode,
  loading,
  editing = false,
  onContentChange,
  onDateChange,
  onViewModeChange,
  onCancelEdit,
}: NoteFormProps) {
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const previewRef = useRef<HTMLDivElement>(null)
  const [showPreview, setShowPreview] = useState(false)

  // 自动聚焦
  useEffect(() => {
    if (textareaRef.current) {
      setTimeout(() => {
        textareaRef.current?.focus()
      }, 100)
    }
  }, [])

  return (
    <div className="space-y-4">
      {/* 内容编辑区域 - 推特风格，简洁专业 */}
      <Card variant="default" size="lg" shadow={false} className="relative">
        <DecorativeLine />
        
        <textarea
          ref={textareaRef}
          id="content"
          value={content}
          onChange={(e) => onContentChange(e.target.value)}
          className="w-full px-0 py-0 border-none text-lg leading-relaxed dark:bg-transparent dark:text-zinc-100 bg-transparent text-zinc-900 resize-none overflow-y-auto focus:outline-none focus:ring-0 focus:ring-offset-0 focus-visible:outline-none focus-visible:ring-0 transition-all placeholder:text-zinc-400 dark:placeholder:text-zinc-600"
          style={{ 
            minHeight: "200px",
            maxHeight: "none",
            outline: "none"
          }}
          required
          title=""
          placeholder="记录这一刻的想法..."
          autoFocus
          onFocus={(e) => {
            e.target.style.outline = "none"
            e.target.style.boxShadow = "none"
            e.target.style.border = "none"
          }}
        />
      </Card>
      
      {/* 底部操作栏 - 推特风格，简洁专业 */}
      <div className="flex items-center justify-between pt-2 px-1">
        <div className="flex items-end gap-3">
          <DatePicker
            value={date}
            onChange={onDateChange}
            placeholder="选择日期"
            className="h-8 text-xs w-auto min-w-[130px] px-3"
          />
          <div className="text-xs text-zinc-400 dark:text-zinc-500 font-mono hidden sm:block opacity-40 pb-0.5">
            {autoGeneratedId}
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={() => setShowPreview(!showPreview)}
            className={cn(
              "h-8 px-3 rounded-lg text-xs font-medium",
              "text-zinc-500 dark:text-zinc-400",
              "hover:bg-zinc-100 dark:hover:bg-zinc-800 hover:text-zinc-700 dark:hover:text-zinc-200 transition-all"
            )}
          >
            {showPreview ? "隐藏预览" : "预览"}
          </Button>
          {editing && onCancelEdit && (
            <Button
              type="button"
              variant="outline"
              onClick={onCancelEdit}
              className={cn(
                "h-9 px-6 rounded-xl text-sm font-medium",
                "bg-white dark:bg-zinc-800 border border-zinc-300 dark:border-zinc-700",
                "text-zinc-700 dark:text-zinc-300",
                "hover:bg-zinc-50 dark:hover:bg-zinc-700"
              )}
            >
              取消编辑
            </Button>
          )}
          <SubmitButton
            loading={loading}
            editing={editing}
            disabled={!content.trim()}
            className={cn(!content.trim() && "opacity-50")}
          />
        </div>
      </div>
      
      {/* 预览区域 - 可选显示 */}
      {showPreview && (
        <Card variant="muted" size="md" className="overflow-y-auto" style={{ minHeight: "200px", maxHeight: "400px" }}>
          <div ref={previewRef}>
            <NotePreview content={content} date={date} />
          </div>
        </Card>
      )}
    </div>
  )
}
