"use client"

import { useRef, useEffect, useState } from "react"
import { Button } from "@/components/ui/button"
import { DatePicker } from "@/components/ui/date-picker"
import { NotePreview } from "@/components/note-preview"
import { Loader2 } from "lucide-react"
import { cn } from "@/lib/utils"

type ViewMode = "edit" | "preview" | "split"

interface NoteFormProps {
  content: string
  date: string
  autoGeneratedId: string
  viewMode: ViewMode
  loading: boolean
  onContentChange: (content: string) => void
  onDateChange: (date: string) => void
  onViewModeChange: (mode: ViewMode) => void
}

export function NoteForm({
  content,
  date,
  autoGeneratedId,
  viewMode,
  loading,
  onContentChange,
  onDateChange,
  onViewModeChange,
}: NoteFormProps) {
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const previewRef = useRef<HTMLDivElement>(null)
  const [showPreview, setShowPreview] = useState(false)

  // 自动聚焦
  useEffect(() => {
    if (textareaRef.current) {
      setTimeout(() => {
        textareaRef.current?.focus()
      }, 100)
    }
  }, [])

  return (
    <div className="space-y-4">
      {/* 内容编辑区域 - 推特风格，简洁专业 */}
      <div className="relative bg-stone-50 dark:bg-zinc-900/50 rounded-xl border border-zinc-200 dark:border-zinc-800 p-6 shadow-sm transition-all">
        {/* 精致的装饰线 */}
        <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-zinc-200 dark:via-zinc-700 to-transparent"></div>
        
        <textarea
          ref={textareaRef}
          id="content"
          value={content}
          onChange={(e) => onContentChange(e.target.value)}
          className="w-full px-0 py-0 border-none text-lg leading-relaxed dark:bg-transparent dark:text-zinc-100 bg-transparent text-zinc-900 resize-none overflow-y-auto focus:outline-none focus:ring-0 focus:ring-offset-0 focus-visible:outline-none focus-visible:ring-0 transition-all placeholder:text-zinc-400 dark:placeholder:text-zinc-600"
          style={{ 
            minHeight: "200px",
            maxHeight: "none",
            outline: "none"
          }}
          required
          placeholder="记录这一刻的想法..."
          autoFocus
          onFocus={(e) => {
            e.target.style.outline = "none"
            e.target.style.boxShadow = "none"
            e.target.style.border = "none"
          }}
        />
      </div>
      
      {/* 底部操作栏 - 推特风格，简洁专业 */}
      <div className="flex items-center justify-between pt-2 px-1">
        <div className="flex items-end gap-3">
          <DatePicker
            value={date}
            onChange={onDateChange}
            placeholder="选择日期"
            className="h-8 text-xs w-auto min-w-[130px] px-3"
          />
          <div className="text-xs text-zinc-400 dark:text-zinc-500 font-mono hidden sm:block opacity-40 pb-0.5">
            {autoGeneratedId}
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={() => setShowPreview(!showPreview)}
            className={cn(
              "h-8 px-3 rounded-lg text-xs font-medium",
              "text-zinc-500 dark:text-zinc-400",
              "hover:bg-zinc-100 dark:hover:bg-zinc-800 hover:text-zinc-700 dark:hover:text-zinc-200 transition-all"
            )}
          >
            {showPreview ? "隐藏预览" : "预览"}
          </Button>
          <button
            type="submit"
            disabled={loading || !content.trim()}
            className={cn(
              "h-9 px-6 rounded-xl text-sm font-medium",
              "bg-zinc-900 text-white dark:bg-zinc-50 dark:text-zinc-900",
              "border border-zinc-900 dark:border-zinc-50",
              "shadow-sm hover:shadow-md transition-all",
              "disabled:opacity-40 disabled:cursor-not-allowed disabled:hover:shadow-sm",
              !content.trim() && "opacity-50"
            )}
          >
            {loading ? (
              <span className="flex items-center gap-2">
                <Loader2 className="w-4 h-4 animate-spin" />
                发布中...
              </span>
            ) : (
              "发布"
            )}
          </button>
        </div>
      </div>
      
      {/* 预览区域 - 可选显示 */}
      {showPreview && (
        <div className="bg-stone-50 dark:bg-zinc-900/50 rounded-xl border border-zinc-200 dark:border-zinc-800 p-6 shadow-sm">
          <div 
            ref={previewRef}
            className="rounded-lg p-4 bg-zinc-50 dark:bg-zinc-800/50 overflow-y-auto"
            style={{ 
              minHeight: "200px",
              maxHeight: "400px"
            }}
          >
            <NotePreview content={content} date={date} />
          </div>
        </div>
      )}
    </div>
  )
}
