"use client"

import { useRef, useEffect, useState } from "react"
import { NotePreview } from "@/components/note-preview"
import { NdDatePicker } from "./nd-date-picker"

type ViewMode = "edit" | "preview" | "split"

interface NoteFormProps {
  content: string
  date: string
  autoGeneratedId: string
  viewMode: ViewMode
  loading: boolean
  editing?: boolean
  onContentChange: (content: string) => void
  onDateChange: (date: string) => void
  onViewModeChange: (mode: ViewMode) => void
  onCancelEdit?: () => void
}

export function NoteForm({
  content,
  date,
  autoGeneratedId,
  loading,
  editing = false,
  onContentChange,
  onDateChange,
  onCancelEdit,
}: NoteFormProps) {
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const [showPreview, setShowPreview] = useState(false)

  useEffect(() => {
    if (textareaRef.current) {
      setTimeout(() => {
        textareaRef.current?.focus()
      }, 100)
    }
  }, [])

  return (
    <div className="space-y-6">
      <div className="nd-surface p-5 md:p-6">
        <p className="nd-label mb-4">随笔</p>
        <textarea
          ref={textareaRef}
          id="content"
          value={content}
          onChange={(e) => onContentChange(e.target.value)}
          className="nd-textarea !font-[var(--font-space-grotesk)] !text-[18px] !leading-relaxed min-h-[200px]"
          placeholder="记录这一刻的想法..."
          required
          autoFocus
        />
      </div>

      <div className="flex items-end justify-between gap-3">
        <div className="flex items-end gap-3 min-w-0 flex-1">
          <div className="min-w-0">
            <p className="nd-label mb-2">日期</p>
            <NdDatePicker
              value={date}
              onChange={onDateChange}
              placeholder="选择日期"
              size="display"
            />
          </div>
          <p className="nd-caption pb-2 hidden sm:block truncate">{autoGeneratedId}</p>
        </div>

        <div className="flex items-center gap-1.5 sm:gap-2 flex-shrink-0">
          <button
            type="button"
            onClick={() => setShowPreview(!showPreview)}
            className="nd-btn nd-btn-ghost !text-[11px] !min-h-[40px] !px-2 sm:!px-3"
          >
            {showPreview ? "隐藏" : "预览"}
          </button>
          {editing && onCancelEdit && (
            <button
              type="button"
              onClick={onCancelEdit}
              className="nd-btn nd-btn-secondary !min-h-[40px] !px-3 sm:!px-4 !py-2 !text-[11px]"
            >
              取消
            </button>
          )}
          <button
            type="submit"
            disabled={loading || !content.trim()}
            className="nd-btn nd-btn-primary !min-h-[40px] !px-4 sm:!px-6 !py-2 !text-[11px]"
          >
            {loading
              ? "提交中..."
              : editing
                ? "更新"
                : "发布"}
          </button>
        </div>
      </div>

      {showPreview && (
        <div
          className="nd-surface p-5 md:p-6 overflow-y-auto"
          style={{ minHeight: "200px", maxHeight: "400px", background: "var(--nd-surface-raised)" }}
        >
          <p className="nd-label mb-3">预览</p>
          <NotePreview content={content} date={date} />
        </div>
      )}
    </div>
  )
}
